project:
  title: "PHI 101"
  type: website

website:
  title: "PHI 101-003"
  site-url: "https://www.davidsanson.com/101"
  page-footer: |
    © 2026 David Sanson. Created using [Quarto](https://quarto.org/).
  navbar:
    aria-label: navigation
    left:
      - href: index.md
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: schedule.md
        text: Schedule
      - href: https://www.davidsanson.com/learning-from-arguments-remix/
        text: Textbook

bibliography: [references.json]
citeproc: true
filters:
  - label-bullets.lua

metadata:
  author:
  - name: David Sanson
  course: phi101

callout-appearance: minimal

tbl-cap-location: bottom

format:
  html:
    template-partials:
      - title-metadata.html
    respect-user-color-scheme: true
    theme:
      light: 
        - flatly
        - custom.scss
      dark: 
        - darkly
        - custom.scss

    # format-links:
    # - html
    # - format: typst
    #   icon: file-pdf
    #   text: PDF

  # typst:
  #   citeproc: true
  #   template-partials:
  #   - typst-template.typ
  #   fontsize: 10pt
  #   mainfont: Minion Pro
  #   sansfont: Myriad Pro
  #   margin:
  #     x: 1in
  #     y: 1in
  #   papersize: us-letter
  #
    #pdf-standard: ua-1


